export const message = {
    UNAUTHORIZED: "Unauthorized. Please login",
    INVALID_LOGIN: "Invalid email or password",
    LOGIN_SUCCESS: "Login successful",
    USER_NOT_FOUND: "User not found",
    EMPLOYEE_CREATED: "Employee created successfully",
    EMPLOYEE_UPDATED: "Employee updated successfully",
    EMPLOYEE_DELETED: "Employee deleted successfully",
    EMPLOYEE_NOT_FOUND: "Employee not found",
    EMPLOYEE_STATUS_UPDATED: "Employee status updated successfully",
    INVALID_TOKEN: "Invalid token. Please login again",
    TOKEN_EXPIRED: "Token has expired. Please login again",
    CUSTOMER_CREATED: "Customer created successfully",
    CUSTOMER_UPDATED: "Customer updated successfully",
    CUSTOMER_DELETED: "Customer deleted successfully",
    CUSTOMER_NOT_FOUND: "Customer not found",
    INVALID_CUSTOMER_ID: "Invalid customer ID",
    CUSTOMER_STATUS_UPDATED: "Customer status updated successfully",
    STORE_CREATED: "Store created successfully",
    STORE_UPDATED: "Store updated successfully",
    STORE_DELETED: "Store deleted successfully",
    STORE_NOT_FOUND: "Store not found",
    STORE_STATUS_UPDATED: "Store status updated successfully",
    INVALID_STORE_ID: "Invalid store ID",
    COUNTRY_CREATED: "Country created successfully",
    COUNTRY_UPDATED: "Country updated successfully",
    COUNTRY_DELETED: "Country deleted successfully",
    COUNTRY_NOT_FOUND: "Country not found",
    INVALID_COUNTRY_ID: "Invalid country ID",
    COUNTRY_STATUS_UPDATED: "Country status updated successfully",
    DELIVERY_PARTNER_CREATED: "Delivery partner created successfully",
    DELIVERY_PARTNER_UPDATED: "Delivery partner updated successfully",
    DELIVERY_PARTNER_DELETED: "Delivery partner deleted successfully",
    DELIVERY_PARTNER_NOT_FOUND: "Delivery partner not found",
    INVALID_DELIVERY_PARTNER_ID: "Invalid delivery partner ID",
    DELIVERY_PARTNER_STATUS_UPDATED: "Delivery partner status updated successfully",
    PICKUP_PARTNER_CREATED: "Pickup partner created successfully",
    PICKUP_PARTNER_UPDATED: "Pickup partner updated successfully",
    PICKUP_PARTNER_DELETED: "Pickup partner deleted successfully",
    PICKUP_PARTNER_NOT_FOUND: "Pickup partner not found",
    INVALID_PICKUP_PARTNER_ID: "Invalid pickup partner ID",
    PICKUP_PARTNER_STATUS_UPDATED: "Pickup partner status updated successfully",
    PRICING_CREATED: "Pricing created successfully",
    PRICING_UPDATED: "Pricing updated successfully",
    PRICING_DELETED: "Pricing deleted successfully",
    PRICING_NOT_FOUND: "Pricing not found",
    INVALID_PRICING_ID: "Invalid pricing ID",
    PRODUCT_CREATED: "Product created successfully",
    PRODUCT_UPDATED: "Product updated successfully",
    PRODUCT_DELETED: "Product deleted successfully",
    PRODUCT_NOT_FOUND: "Product not found",
    INVALID_PRODUCT_ID: "Invalid product ID",
    PRODUCT_STATUS_UPDATED: "Product status updated successfully",
    FABRIC_CREATED: "Fabric created successfully",
    FABRIC_UPDATED: "Fabric updated successfully",
    FABRIC_DELETED: "Fabric deleted successfully",
    FABRIC_NOT_FOUND: "Fabric not found",
    INVALID_FABRIC_ID: "Invalid fabric ID",
    FABRIC_STATUS_UPDATED: "Fabric status updated successfully",
    PICKUP_ASSIGN_CREATED: "Pickup assign created successfully",
    PICKUP_ASSIGN_UPDATED: "Pickup assign updated successfully",
    PICKUP_ASSIGN_DELETED: "Pickup assign deleted successfully",
    PICKUP_ASSIGN_NOT_FOUND: "Pickup assign not found",
    INVALID_PICKUP_ASSIGN_ID: "Invalid pickup assign ID",
    PICKUP_ASSIGN_STATUS_UPDATED: "Pickup assign status updated successfully",
    PICKUP_ASSIGN_COLLECTED: "Pickup assign marked as collected successfully",
    PICKUP_ASSIGN_PAYMENT_STATUS_UPDATED: "Pickup assign payment status updated successfully",
    INVALID_PICKUP_ASSIGN_PAYMENT_STATUS: "Invalid pickup assign payment status",
    INVALID_PICKUP_ASSIGN_PICKUP_STATUS: "Invalid pickup assign pickup status",
    PRE_BOOKING_CREATED: "Pre-booking created successfully",
    PRE_BOOKING_UPDATED: "Pre-booking updated successfully",
    PRE_BOOKING_DELETED: "Pre-booking deleted successfully",
    PRE_BOOKING_NOT_FOUND: "Pre-booking not found",
    INVALID_PREBOOKING_ID: "Invalid pre-booking ID",
    PRE_BOOKING_STATUS_UPDATED: "Pre-booking status updated successfully",
    INVALID_PRE_BOOKING_ID: "Invalid pre-booking ID",
    BOOKING_CREATED: "Booking created successfully",
    BOOKING_UPDATED: "Booking updated successfully",
    BOOKING_DELETED: "Booking deleted successfully",
    BOOKING_NOT_FOUND: "Booking not found",
    BOOKING_STATUS_UPDATED: "Booking status updated successfully",
    INVALID_BOOKING_ID: "Invalid booking ID",



};