export const message = {
    UNAUTHORIZED: "Unauthorized. Please login",
    INVALID_LOGIN: "Invalid email or password",
    LOGIN_SUCCESS: "Login successful",
    USER_NOT_FOUND: "User not found",
    EMPLOYEE_CREATED: "Employee created successfully",
    EMPLOYEE_UPDATED: "Employee updated successfully",
    EMPLOYEE_DELETED: "Employee deleted successfully",
    EMPLOYEE_NOT_FOUND: "Employee not found",
    EMPLOYEE_STATUS_UPDATED: "Employee status updated successfully",
    INVALID_TOKEN: "Invalid token. Please login again",
    TOKEN_EXPIRED: "Token has expired. Please login again",
    CUSTOMER_CREATED: "Customer created successfully",
    CUSTOMER_UPDATED: "Customer updated successfully",
    CUSTOMER_DELETED: "Customer deleted successfully",
    CUSTOMER_NOT_FOUND: "Customer not found",
    INVALID_CUSTOMER_ID: "Invalid customer ID",
    CUSTOMER_STATUS_UPDATED: "Customer status updated successfully",
    STORE_CREATED: "Store created successfully",
    STORE_UPDATED: "Store updated successfully",
    STORE_DELETED: "Store deleted successfully",
    STORE_NOT_FOUND: "Store not found",
    STORE_STATUS_UPDATED: "Store status updated successfully",
    INVALID_STORE_ID: "Invalid store ID",
    COUNTRY_CREATED: "Country created successfully",
    COUNTRY_UPDATED: "Country updated successfully",
    COUNTRY_DELETED: "Country deleted successfully",
    COUNTRY_NOT_FOUND: "Country not found",
    INVALID_COUNTRY_ID: "Invalid country ID",
    COUNTRY_STATUS_UPDATED: "Country status updated successfully",
    DELIVERY_PARTNER_CREATED: "Delivery partner created successfully",
    DELIVERY_PARTNER_UPDATED: "Delivery partner updated successfully",
    DELIVERY_PARTNER_DELETED: "Delivery partner deleted successfully",
    DELIVERY_PARTNER_NOT_FOUND: "Delivery partner not found",
    INVALID_DELIVERY_PARTNER_ID: "Invalid delivery partner ID",
    DELIVERY_PARTNER_STATUS_UPDATED: "Delivery partner status updated successfully",

};