export const message = {
    UNAUTHORIZED: "Unauthorized. Please login",
    INVALID_LOGIN: "Invalid email or password",
    LOGIN_SUCCESS: "Login successful",
    USER_NOT_FOUND: "User not found",
    EMPLOYEE_CREATED: "Employee created successfully",
    EMPLOYEE_UPDATED: "Employee updated successfully",
    EMPLOYEE_DELETED: "Employee deleted successfully",
    EMPLOYEE_NOT_FOUND: "Employee not found",
    EMPLOYEE_STATUS_UPDATED: "Employee status updated successfully",
    INVALID_TOKEN: "Invalid token. Please login again",
    TOKEN_EXPIRED: "Token has expired. Please login again",
    CUSTOMER_CREATED: "Customer created successfully",
    CUSTOMER_UPDATED: "Customer updated successfully",
    CUSTOMER_DELETED: "Customer deleted successfully",
    CUSTOMER_NOT_FOUND: "Customer not found",
    INVALID_CUSTOMER_ID: "Invalid customer ID",
    CUSTOMER_STATUS_UPDATED: "Customer status updated successfully",

};